name: test & release
on:
  push:
    branches-ignore:
      - main
      - dummy_main
    tags:
      - release-*
      - prerelease-*

jobs:
  build:
    name: build bottle on ${{matrix.target.name}}
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        const:
          - as_release: ${{ startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-') }}
            is_release: ${{ startsWith(github.ref,'refs/tags/release-') }}
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
    #   - name: install dependencies
    #     run: |
    #       brew upgrade
    #       brew 
    #   - name: checkout quantum espresso
    #     uses: actions/checkout@v4
    #     with:
    #       repository: QEF/q-e
    #       ref: develop
    #       path: q-e
    #   - name: set build cache
    #     uses: actions/cache@v4
    #     with:
    #       path: |
    #         ${{ github.workspace }}/.cache/src
    #         ${{ github.workspace }}/.nginx
    #         ${{ github.workspace }}/target
    #       key: src+${{matrix.target.name}}+${{matrix.target.ngx}}+${{github.run_id}}
    #       restore-keys: src+${{matrix.target.name}}+${{matrix.target.ngx}}+
      - name: checkout
        run: |
          brew tap JyJyJcr/materiapps
          cd "$(brew --repo JyJyJcr/materiapps)"
          git fetch
          git checkout ${{github.sha}}
          cd -
      - name: build bottle
        run: |
          brew install --build-bottle JyJyJcr/materiapps/quantum-espresso
          brew bottle --json JyJyJcr/materiapps/quantum-espresso
      - name: upload bottle
        uses: actions/upload-artifact@v4
        with:
          name: bottle+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.tar.gz
      - name: upload json
        uses: actions/upload-artifact@v4
        with:
          name: json+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.json
  publish:
    name: publish bottle
    needs: build
    runs-on: ubuntu-latest
    # environment:
    #   name: publish
    permissions:
      contents: write
      actions: write
    if: startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-')
    steps:
      - name: checkout
        run: |
          brew tap JyJyJcr/materiapps
          cd "$(brew --repo JyJyJcr/materiapps)"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }}
          cd -
      - name: set gitconfig
        run: |
          cd "$(brew --repo JyJyJcr/materiapps)"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          cd -
      - name: merge
        run: |
          cd "$(brew --repo JyJyJcr/materiapps)"
          git merge ${{github.sha}} -m "ci: catch up to ${{github.ref_name}}"
          cd -
      - name: download bottle
        uses: actions/download-artifact@v4
        with:
          pattern: bottle+*
          merge-multiple: true
          path: ./
      - name: download json
        uses: actions/download-artifact@v4
        with:
          pattern: json+*
          merge-multiple: true
          path: ./
      - name: commit
        run: |
          for json in quantum-espresso-*.json;do
            brew bottle --merge --write $json
          done
      # - name: push
      #   run: |
      #     cd "$(brew --repo JyJyJcr/materiapps)"
      #     git push
      #     cd -
