name: test & release
on:
  push:
    branches-ignore:
      - main
      - dummy_main
    tags:
      - release-*
      - prerelease-*

jobs:
  build:
    name: build bottle on ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        const:
          - as_release: ${{ startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-') }}
            is_release: ${{ startsWith(github.ref,'refs/tags/release-') }}
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: checkout
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git checkout ${{github.sha}}
          cd -
      - name: build bottle
        run: |
          brew install --build-bottle ${{ github.repository }}/quantum-espresso
          brew bottle --json --root-url "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}" ${{ github.repository }}/quantum-espresso
      - name: upload bottle
        uses: actions/upload-artifact@v4
        with:
          name: bottle+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.tar.gz
      - name: upload json
        uses: actions/upload-artifact@v4
        with:
          name: json+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.json
  publish_formula:
    name: publish formula
    needs: build
    runs-on: macos-latest
    # environment:
    #   name: publish
    permissions:
      contents: write
      actions: write
    if: startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-')
    steps:
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: checkout
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }}
          cd -
      - name: merge
        run: |
          cd "$(brew --repo ${{ github.repository }})"
          git merge ${{github.sha}} -m "ci: catch up to ${{github.ref_name}}"
          cd -
      - name: download json
        uses: actions/download-artifact@v4
        with:
          pattern: json+*
          merge-multiple: true
          path: ./
      - name: commit
        run: |
          brew bottle --merge --write quantum-espresso-*.json
      - name: push
        run: |
          cd "$(brew --repo ${{ github.repository }})"
          git push https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git
          cd -
  publish_bottle:
    name: publish bottle
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    if: startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-')
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: download bottle
        uses: actions/download-artifact@v4
        with:
          pattern: bottle+*
          merge-multiple: true
          path: ./
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ startsWith(github.ref,'refs/tags/prerelease-') }}
          files: |
            quantum-espresso-*.tar.gz
  test:
    name: test bottle on ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.host }}
    if: startsWith(github.ref,'refs/tags/release-')|| startsWith(github.ref,'refs/tags/prerelease-')
    needs:
      - publish_bottle
      - publish_formula
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: checkout
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }}
          cd -
      - name: install
        run: |
          brew install quantum-espresso
