name: release
on:
  push:
    tags:
      - release-*
      - prerelease-*

jobs:
  merge:
    name: merge ${{ github.ref_name }} to ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
      - name: reset & merge & push
        run: |
          git fetch
          git reset --hard ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }} --
          git merge ${{github.sha}} -m "ci: catch up to ${{github.ref_name}}"
          git push -f https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git

  build:
    name: build bottle on ${{ matrix.target.name }}
    needs: merge
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: brew tap from ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
          cd -
      - name: build bottle
        run: |
          brew install --build-bottle ${{ github.repository }}/quantum-espresso
          brew bottle --json --root-url "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}" ${{ github.repository }}/quantum-espresso
      - name: upload bottle
        uses: actions/upload-artifact@v4
        with:
          name: bottle+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.tar.gz
      - name: upload bottle info json
        uses: actions/upload-artifact@v4
        with:
          name: json+${{ matrix.target.name }}
          path: |
            quantum-espresso-*.json
  publish_formula:
    name: publish formula
    needs:
      - merge
      - build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: brew tap from ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
          cd -
      - name: download bottle info json
        uses: actions/download-artifact@v4
        with:
          pattern: json+*
          merge-multiple: true
          path: ./
      - name: commit
        run: |
          brew bottle --merge --write quantum-espresso-*.json
      - name: push
        run: |
          cd "$(brew --repo ${{ github.repository }})"
          git push https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git
          cd -
  publish_bottle:
    name: publish bottle
    needs: build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: download bottle
        uses: actions/download-artifact@v4
        with:
          pattern: bottle+*
          merge-multiple: true
          path: ./
      - name: brew upgrade
        run: |
          brew upgrade
      - name: replace bottle name
        run: |
          brew install rename
          rename -s -- - quantum-espresso-*.tar.gz
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ startsWith(github.ref,'refs/tags/prerelease-') }}
          files: |
            quantum-espresso-*.tar.gz
  test:
    name: test bottle on ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.host }}
    needs:
      - publish_bottle
      - publish_formula
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: brew tap from ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
          cd -
      - name: brew install from bottle
        run: |
          brew install quantum-espresso
  commit:
    name: commit ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }} to ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }}
    needs: test
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ startsWith(github.ref,'refs/tags/release-') && 'main' || 'dummy_main' }}
      - name: reset & push
        run: |
          git fetch
          git reset --hard ${{ startsWith(github.ref,'refs/tags/release-') && 'main_tmp' || 'dummy_main_tmp' }} --
          git push https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git

