name: release
on:
  push:
    tags:
      - release/*/*
      - prerelease/*/*

jobs:
  configure:
    name: configure
    runs-on: macos-latest
    outputs:
      formula: ${{ steps.get_formula.outputs.formula }}
      is_release: ${{ startsWith(github.ref,'refs/tags/release/') }}
      deploy_branch: ${{ startsWith(github.ref,'refs/tags/release/') && 'main' || 'dummy_main' }}
      work_branch: ${{ startsWith(github.ref,'refs/tags/release/') && 'main_tmp' || 'dummy_main_tmp' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get formula from tag
        id: get_formula
        run: |
          formula="$(echo ${{ github.ref_name }} | awk -F'[\\\\/]' ' { print $2 }')"
          [ -f "Formula/$formula.rb" ]
          echo "formula=$formula" >> $GITHUB_OUTPUT

  merge:
    name: merge ${{ github.ref_name }} to ${{ needs.configure.outputs.work_branch }}
    runs-on: macos-latest
    needs:
      - configure
    permissions:
      contents: write
    steps:
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.configure.outputs.work_branch }}
          fetch-depth: 0
      - name: reset & merge & push
        run: |
          git reset --hard origin/${{ needs.configure.outputs.deploy_branch }} --
          git merge ${{github.sha}} -m "ci: catch up to ${{github.ref_name}}"
          git push -f https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git

  build:
    name: build bottle of ${{ needs.configure.outputs.formula }} on ${{ matrix.target.name }}
    needs:
      - configure
      - merge
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: brew tap from ${{ needs.configure.outputs.work_branch }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ needs.configure.outputs.work_branch }}
          cd -
      - name: build bottle
        run: |
          brew install --build-bottle ${{ github.repository }}/${{ needs.configure.outputs.formula }}
          brew bottle --json --root-url "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}" ${{ github.repository }}/${{ needs.configure.outputs.formula }}
      - name: upload bottle
        uses: actions/upload-artifact@v4
        with:
          name: bottle+${{ matrix.target.name }}
          path: |
            ${{ needs.configure.outputs.formula }}-*.tar.gz
      - name: upload bottle info json
        uses: actions/upload-artifact@v4
        with:
          name: json+${{ matrix.target.name }}
          path: |
            ${{ needs.configure.outputs.formula }}-*.json
  publish_formula:
    name: publish formula
    needs:
      - configure
      - merge
      - build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: brew tap from ${{ needs.configure.outputs.work_branch }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ needs.configure.outputs.work_branch }}
          cd -
      - name: download bottle info json
        uses: actions/download-artifact@v4
        with:
          pattern: json+*
          merge-multiple: true
          path: ./
      - name: commit
        run: |
          brew bottle --merge --write ${{ needs.configure.outputs.formula }}-*.json
      - name: push
        run: |
          cd "$(brew --repo ${{ github.repository }})"
          git push https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git
          cd -
  publish_bottle:
    name: publish bottle
    needs:
      - configure
      - build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: download bottle
        uses: actions/download-artifact@v4
        with:
          pattern: bottle+*
          merge-multiple: true
          path: ./
      - name: brew upgrade
        run: |
          brew upgrade
      - name: replace bottle name
        run: |
          brew install rename
          rename -s -- - ${{ needs.configure.outputs.formula }}-*.tar.gz
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ ! needs.configure.outputs.is_release }}
          files: |
            ${{ needs.configure.outputs.formula }}-*.tar.gz
  test:
    name: test bottle on ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.host }}
    needs:
      - configure
      - publish_bottle
      - publish_formula
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: brew tap from ${{ needs.configure.outputs.work_branch }}
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git switch ${{ needs.configure.outputs.work_branch }}
          cd -
      - name: brew install from bottle
        run: |
          brew install ${{ github.repository }}/${{ needs.configure.outputs.formula }}
  commit:
    name: sync ${{ needs.configure.outputs.deploy_branch }} to ${{ needs.configure.outputs.work_branch }}
    needs:
      - configure
      - test
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: set gitconfig
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.configure.outputs.deploy_branch }}
          fetch-depth: 0
      - name: reset & push
        run: |
          git reset --hard origin/${{ needs.configure.outputs.work_branch }} --
          git push https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git

