name: test
on:
  push:
    branches-ignore:
      - main
      - dummy_main

jobs:
  build:
    name: test on ${{ matrix.target.name }}
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        target:
          - name: osx_arm64
            host: macos-14
          - name: osx_amd64
            host: macos-13
    steps:
      - name: brew upgrade
        run: |
          brew upgrade
      - name: brew tap from this commit
        run: |
          brew tap ${{ github.repository }}
          cd "$(brew --repo ${{ github.repository }})"
          git fetch
          git checkout ${{github.sha}}
          cd -
      - name: brew install from source
        run: |
          brew install ${{ github.repository }}/quantum-espresso
      # - name: brew test
      #   run: |
      #     brew test ${{ github.repository }}/quantum-espresso
